<div class="page-title">
    <h1><?php echo $this->__('Delete Account') ?></h1>
</div>

<div>
    <p>If you proceed to delete your account, all data we hold about you will be destroyed or anonymised. This operation cannot be un-done.</p>
    <br>
    <button type="button" title="<?php echo $this->__('Delete my account') ?>" class="button" onclick="window.location='<?php echo '/gaiterjones_gdpr/customer/deleteaccount/' ?>';"><span><span><?php echo $this->__('Delete my account') ?></span></span></button>
</div>

