<?php $_helper = Mage::helper('gaiterjones_gdpr'); ?>
<?php
if(Mage::getStoreConfig('gaiterjones_gdpr/options/enabled'))
{
?>
<div id="gdprcookiealert" class="gdpr-bar gdpr-dark-clean gdpr-top" style="display: none;">
	<div class="gdpr-message">
		<span class="gdpr-title"><?php echo ($_helper->getShow() == 'default') ? $this->__("Cookie Policy") : $_helper->getCustomTitleText(); ?></span>
		<p>
			<?php echo ($_helper->getShow() == 'default') ? $this->__('This site uses cookies and other tracking technologies to assist with navigation and your ability to provide feedback, analyse your use of our products and services, assist with our promotional and marketing efforts, and provide content from third parties.') : $_helper->getCustomMessage(); ?>
		</p>
	</div>
	<div class="gdpr-actions">
		<a class="gdpr-button gdpr-accept" href="javascript:acceptCookieAlert();">&nbsp;<?php echo ($_helper->getShow() == 'default') ? $this->__("Accept") : $_helper->getCustomAccept(); ?></a>
		<a class="gdpr-button gdpr-decline" href="javascript:declineCookieAlert();">&nbsp;<?php echo ($_helper->getShow() == 'default') ? $this->__("Decline") : $_helper->getCustomDecline(); ?></a>
		<a class="gdpr-button" href="<?php echo $this->getCmsPageUrl(); ?>"><?php echo ($_helper->getShow() == 'default') ? $this->__("More information") : $_helper->getCustomMoreInfo(); ?></a>
	</div>
</div>

<script type="text/javascript">
function closeCookieAlert() {
    Mage.Cookies.set('cookieAlertClosedFlag', 1, new Date(new Date().getTime() + (1000 * 60 * 60 * 24 * 364)));
    document.getElementById('gdprcookiealert').style.display = 'none';
}

function acceptCookieAlert() {
    closeCookieAlert();
    Mage.Cookies.set('cookieAlertState', 1, new Date(new Date().getTime() + (1000 * 60 * 60 * 24 * 364)));
    loadCookieScript();
}

function declineCookieAlert() {
    closeCookieAlert();
    Mage.Cookies.set('cookieAlertState', 0, new Date(new Date().getTime() + (1000 * 60 * 60 * 24 * 364)));
}

function loadCookieScript() {
<?php
$gtmContainerId = Mage::getStoreConfig('gaiterjones_gdpr/configuration/gtm_container_id');
if (!empty($gtmContainerId)) {
    ?>
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.text = 'var Translator = new Translate([]);';
    document.body.appendChild(script);

    var gtm_tag = document.createElement('script');
    gtm_tag.type = 'text/javascript';
    gtm_tag.text = '(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);})(window,document,\'script\',\'dataLayer\',\'<?php echo $gtmContainerId; ?>\');';
    document.body.appendChild(gtm_tag);
    <?php
}
?>
}

if (!Mage.Cookies.get('cookieAlertClosedFlag')) {
    document.getElementById('gdprcookiealert').style.display = '';
}

if (Mage.Cookies.get('cookieAlertState') == 1) {
    loadCookieScript();
}
</script>
	<?php
}
